### ISSUE TITLE
Sprite3D would be called Sprite3d in Bevy

### ISSUE THREAD

**Issue by mgi388** [merwaaan/bevy_spritesheet_animation#11]
Feel free to just close this if you don't want to change it, but in Bevy the 3D types are named `Foo3d` rather than `Foo3D`:

<img width="289" alt="image" src="https://github.com/user-attachments/assets/e0b4b638-eed3-46ed-9dcf-4287b90d78fc">

**Comment by merwaaan** [comment]
I'm all for consistency! I'll change that, thanks for the feedback.
