### ISSUE TITLE
Error when using bevy_picking_raycast feature in bevy_mod_picking due to PrimitiveTopology

### ISSUE THREAD

**Issue by mgi388** [merwaaan/bevy_spritesheet_animation#14]
The error is:

```
ERROR bevy_mod_raycast::raycast: Invalid intersection check: `TriangleList` is the only supported `PrimitiveTopology`
```

From here: https://github.com/aevyrie/bevy_mod_raycast/blob/dbc5ef32fe48997a1a7eeec7434d9dd8b829e52e/src/raycast.rs#L18-L20

Would it be possible to change the `PrimitiveTopology` here: https://github.com/merwaaan/bevy_spritesheet_animation/blob/1b55379bc6141a7028013a941499e8053e44174c/src/systems/sprite3d.rs#L72

To `TriangleList`? I know it would require some vertices restructuring, but hopefully possible. I also note that `bevy_sprite3d` also uses `TriangleList`: https://github.com/FraserLee/bevy_sprite3d/blob/ce57326ff63b1dae99cd2595422672bc82b22325/src/lib.rs#L123

----

I think to replicate the error (if you needed to know), you just need to spawn some `Sprite3d`s, and have bevy_mod_picking in your app, and then just hover over one of the entities.

**Comment by merwaaan** [comment]
Done in https://github.com/merwaaan/bevy_spritesheet_animation/commit/7bb57d9bff72711abbcc807b596eb8c8d37e765a 👍
