### ISSUE TITLE
Thoughts on using std::time::Duration instead of u32 + "milliseconds" in docs

### ISSUE THREAD

**Issue by mgi388** [merwaaan/bevy_spritesheet_animation#2]
E.g. in https://github.com/merwaaan/bevy_spritesheet_animation/blob/2d16821012fddd03cd7d702ba853adfa3e3c3c76/src/animation.rs#L22-L27

Callers rely on reading the docs to see that the duration needs to be milliseconds (mistakes are possibly easier to make, too).

Would it be worth using https://doc.rust-lang.org/std/time/struct.Duration.html? This would make callers look something like:

```
let clip_id = library.new_clip(|clip| {
    clip..set_default_duration(AnimationDuration::PerFrame(Duration::from_millis(100)));
});
```

(untested).

I know it's more verbose, but it takes the hard-coded millis out of the crate and (arguably) makes the crate less opinionated on the duration format.

**Comment by merwaaan** [comment]
Actually, the first, never-committed, version of the plugin actually used std::time::Duration!

In the end, I switched to u32 milliseconds for the following reasons:

- ✅ std::time::Duration is more verbose, as you mentionned.
- ✅ With animations, we usually work in milliseconds (for per-frame duration) or seconds (for per-cycle durations) but std::time::Duration supports a wider range of time scales that do not fit the way the plugin works (eg. with Duration, users could pick, let's say, a duration of 10 ns, so even though that's not realistic in the context of a game loop, the API would have allowed it).
- ✅ Using milliseconds is consistent with well-known API like [JS setInterval](https://developer.mozilla.org/en-US/docs/Web/API/setInterval).

As for the cons of using u32 milliseconds:

- ❌ Makes it ess obvious what the unit is for new users
  - it's part of the documentation though, and most IDEs display it when typing/hovering such a value

I'm not dead set against switching to std::time::Duration but for the moment I'd say that the pros outweight the cons and that it would not add much value besides just being more idiomatic I guess.

I'll keep this Issue open to let other people weigh in on that topic.

**Comment by mgi388** [comment]
Re the JS comment, I think if JS had been built with Duration from the beginning like modern languages like Go and Rust, then `setInterval` probably would have received a Duration rather than millis 🤷 

Interesting comment re nanos. I suppose I like to think we shouldn't try and predict what users might want to do or restrict users, but practically speaking, I can't see how a duration in nanos would ever be used (except maybe for some sort of testing).

But no problem, thanks for entertaining the idea!
