### ISSUE TITLE
Sprite3d panics

### ISSUE THREAD

**Issue by marijanp** [merwaaan/bevy_spritesheet_animation#21]
What could be the reason for the following line panicing? I have two spawn systems each storing several animations in the library. My game panics just after starting.
https://github.com/merwaaan/bevy_spritesheet_animation/blob/e61a77e105b8f121b59a1039999f27e7bf010fce/src/systems/sprite3d.rs#L280-L283

**Comment by merwaaan** [comment]
Hi @marijanp 

Without more info, I cannot say much. There might be an issue with the entity creation.

Do you instantiate your entities like in the [README](https://github.com/merwaaan/bevy_spritesheet_animation?tab=readme-ov-file#3d-sprites), with an explicit atlas?

If you provide a minimal repro, I can try to take a look.

**Comment by marijanp** [comment]
Ok the bug was a wrong animation by-name lookup.
