### ISSUE TITLE
Support bevy 0.15

### ISSUE THREAD

**Issue by mirsella** [merwaaan/bevy_spritesheet_animation#24]
hello :)

**Comment by merwaaan** [comment]
Required components look nice :)

I'm a bit swamped with work at the moment but I'll take a look whenever I have some free time.

**Comment by mirsella** [comment]
hey ! After looking more at bevy 0.15, i think im gonna transition to the built-in bevy animation with the new events integration, which is better for my use as i only used simple 2d animation with events.

so this issue can be closed if you want, or just know that nothing is pressing, at least on my side !

Thanks a lot for your reactivity and helpfulness with my issue and PRs ! have a good one

**Comment by merwaaan** [comment]
@mirsella Thanks for your help and good luck with your projects :)

**Comment by merwaaan** [comment]
bevy_spritesheet_animation 2.0.0 now supports Bevy 0.15
