### ISSUE TITLE
Cache needs to be cleaned when StandardMaterial assets and Mesh assets are removed

### ISSUE THREAD

**Issue by mgi388** [merwaaan/bevy_spritesheet_animation#25]
- If you have a scene with some entities that have `Sprite3dBundle`s.
- Then you unload your scene (i.e. despawn entities).
- Then Bevy works out that your `StandardMaterial` assets and `Mesh` assets are no longer used, so it unloads them.
- If you load the scene again, the sprites are not rendered.
- This is because the `Cache` still contains its old data.
- You can see this using the inspector.
- Notice that the `materials` entries point to assets that no longer exist.

<img width="1213" alt="image" src="https://github.com/user-attachments/assets/6f2ae253-e4db-4fef-8d5a-ad86230a3c3a" />

- I have been testing a fix. Will hopefully PR shortly.

**Comment by merwaaan** [comment]
Merged!
