### ISSUE TITLE
Bevy 0.14 support

### ISSUE THREAD

**Issue by jgayfer** [merwaaan/bevy_spritesheet_animation#3]
Would love to see this library support Bevy `0.14`!

**Comment by merwaaan** [comment]
Sure, I'll take a look!

**Comment by merwaaan** [comment]
Support for Bevy 0.14 has been contributed by @BLumbye in https://github.com/merwaaan/bevy_spritesheet_animation/commit/28c4b26f758cd4dd3bf778a3954249b1dd2e082b :)
