### ISSUE TITLE
Resetting animations

### ISSUE THREAD

**Issue by UkoeHB** [merwaaan/bevy_spritesheet_animation#5]
Currently it does not seem possible to reset animations on an entity (neither reset in-progress animations, nor restart animations that ended). It looks like this could be done by making `SpritesheetAnimator` public and adding a `reset_animation(entity)` method.

**Comment by merwaaan** [comment]
There's now a reset() method on the

**Comment by merwaaan** [comment]
https://github.com/merwaaan/bevy_spritesheet_animation/commit/0f1b3ba0a3bc8b7fa644fc6fe601f52d3e8d2914 added a reset() method on the SpritesheetAnimation component following your request :)
