### ISSUE TITLE
Ability to start an animation from a specific frame.

### ISSUE THREAD

**Issue by indietyp** [merwaaan/bevy_spritesheet_animation#8]
I am currently using this library to orchestrate a set of directional animations, and it is great at what it does.

I have one question tho, regarding the usage of the library - I'd like to not only change the animation - but also be able to change the frame the animation starts on, this is specifically important for things like bullet animations, where one would maybe want to randomize the starting sprite, or - in my case - the animation of a character rolling, changing the direction of the roll results in the whole animation restarting, which can be quite immersion breaking.

Any ideas how one might be able to solve this?

**Comment by merwaaan** [comment]
Hi @indietyp 

At the moment, specifying the startup frame is not possible.

However I'm currently working on a new API to better control and query the state of animations so I added your request to the TODO list. This should be available with the next minor version (no ETA yet but I'm getting back to it right now after a break).

**Comment by merwaaan** [comment]
@indietyp The latest version exposes a `progress` field in the `SpritesheetAnimation` component for controlling playback manually. This should help you out.

You can check out the `progress` example.
