### ISSUE TITLE
Support variants / frame sets

### ISSUE THREAD

**Issue by mgi388** [merwaaan/bevy_spritesheet_animation#9]
I want to be able to create an animation which is made up of a bunch of frames, but which has a number of _variants_ of those same frames.

This is for billboard sprites in a 3D game where each variant is for one of 8 directions.

So if you have a walk animation made up of 3 frames, you want to pick the 3 frames for the _current_ variant.

Calling systems can set the current variant every frame (if they like). For example, a system might update the current variant to match the relative direction of the sprite to the camera^.

**I don't think it's possible to use the current features of the crate for one main reason.** We need to preserve the existing animation and state rather than asking callers changing the `animation_id` or inserting a new animation so that the animation doesn't reset. Imagine a walk animation is playing. If the camera instantaneously rotates, you want the character's same foot to remain on the ground. I.e. you want to keep playing your walk animation, you just want to switch variants.

I am not sure if there's an industry term for this, but I'm using the term variants. Frame sets may also be a term for this, I'm not sure.

Are you interested in working on a design for this with me?

^ **Simplified system that updates the sprite's animation variant to correspond with the camera's transform relative to the sprite**

```rust
fn update_sprite_directions(
    // ...
) {
    for (mut animation) in q.iter_mut() {
        let direction_count = animation.variant_count as f32;

        let direction = 0.0 // calculate direction ...

        // Callers just need to update the variant they want to show.
        animation.current_variant = direction.floor() as usize;
    }
}
```

**Comment by merwaaan** [comment]
Hi @mgi388 

What you describe seems somewhat related to this other issue: https://github.com/merwaaan/bevy_spritesheet_animation/issues/8

I'm currently working on it and I'll add your request to the TODO list.

Do you have more info about this variant-based strategy? Maybe code from some games using this method or some blog articles? I'm not familiar with it but it sounds interesting.

**Comment by merwaaan** [comment]
(Also, the next update will better support 3D sprites out of the box so that might help with your project)

**Comment by mgi388** [comment]
> What you describe seems somewhat related to this other issue: #8

I didn't actually realise #8 mentioned "changing the direction of the roll results in the whole animation restarting, which can be quite immersion breaking". I missed that when I read the issue and thought it was really just about "Ability to start an animation from a specific frame".

> Do you have more info about this variant-based strategy? Maybe code from some games using this method or some blog articles? I'm not familiar with it but it sounds interesting.

I've yet to find anything from other engines or blog articles that describes this feature, but I might be looking for the wrong terminology.

I have a really hacky version locally that works, but I don't think the API is right, so bear with me. Let me share it:

```rust
fn setup_animations(mut commands: Commands, mut library: ResMut<SpritesheetLibrary>) {
    let walk_clip_id = library.new_clip(|clip| {
        clip.push_frame_indices([0, 1, 2, 3])
            .set_default_duration(AnimationDuration::PerFrame(100));
    });
    let walk_anim_id = library.new_animation(|animation| {
        animation
            .add_stage(walk_clip_id.into())
            .set_repeat(AnimationRepeat::Loop);
    });
}
```

When calling `push_frame_indices`, frames 0, 1, 2 and 3 are not indexes into the sprite sheet, but they are saying "I want 4 frames, in order, from the sprite sheet, but I expect that bevy_spritesheet_animation will take care of adjusting this index based on the current variant".

When you spawn an entity, you pass `SpritesheetAnimation`:

```rust
fn spawn_entity() {
    commands.spawn(SpritesheetAnimation::from_id(my_animations.walk).with_variants(0, 8));
}
```

The 8 is the number of directions. In my case I have some sprite sheets with 16 directions. The 0 is `variants_base_atlas_index`. This is required because some sprite sheets don't start their variants at index 0. E.g. in my case, I have a sprite sheet that has 8 frames at the start (for 8 directions to represent character death), and _then_ it's followed by variants (with 16 directions). In that example, I inserted `SpritesheetAnimation::from_id(my_animations.other_walk).with_variants(8, 16)`.

Here is the `bevy_spritesheet_animation` that I hacked together to make it work, but as above the API is not right. I just want to share it as a start.

```rust
pub struct SpritesheetAnimation {
    // ...

    /// The index into the atlas where the variants start.
    pub variants_base_atlas_index: usize,

    /// The current variant of the animation, defaults to 0.
    pub current_variant: usize,

    /// The number of variants the animation has, defaults to 1.
    pub variant_count: usize,
}

impl SpritesheetAnimation {
    pub fn from_id(animation_id: AnimationId) -> Self {
        Self {
            // ...
            variants_base_atlas_index: 0,
            current_variant: 0,
            variant_count: 1,
        }
    }

    pub fn with_variants(mut self, base_atlas_index: usize, variant_count: usize) -> Self {
        self.variants_base_atlas_index = base_atlas_index;
        self.variant_count = variant_count;
        self
    }
    // ...
}
```

Inside the `SpritesheetAnimator` it's just a matter of now constructing the correct `index`:

```rust
entity_atlas.index = entity_animation.variants_base_atlas_index
    + next_frame.atlas_index * entity_animation.variant_count
    + entity_animation.current_variant;
```

Given that I've shared the hacky code I used to get something on the screen working, a couple of issues that stand out to me:

- `clip.push_frame_indices([0, 1, 2, 3])` for variants just looks wrong. Readers will think it's pushing the first 4 frames from the root of the sprite sheet, but it's not.
- My current design requires you to call `SpritesheetAnimation::with_variants`, but you should be able to do that at animation creation time. I just attached that to `SpritesheetAnimation` because it was convenient to hack into the animator, but I think we want those fields to be attached to `Animation` or `AnimationClip` (not sure which off the top of my head), and that way we can get `bevy_spritesheet_animation` to compute the actual frames needed, cache them, use the iterator, etc.

I wonder if a design like this might work:

```rust
let walk_clip_id = library.new_clip(|clip| {
    clip.with_variants(16).starting_at_index(8).push_frame_indices([0, 1, 2, 3])
        .set_default_duration(AnimationDuration::PerFrame(100));
});
```

And by default, a clip technically always has one variant (and starts at index 0). It could help internally to model things as variants and by default there's 1, rather than having to build variants as an exception to the design.

I still don't love how `push_frame_indices` doesn't make it clear that you're actually going to get a frame more like 8, 16, 24, 32 (because you step by 8). It may just need a different name. 

Also, it's not really clear to me if the existing "spritesheet from grid, row, row_partial, etc" stuff works for this. Maybe it does. Ultimately I think that just picks some frames to use (?), so if you used it for this, it still picks frames, it's just that those would be adjusted by the variant count.

I can share some sprite sheets if you want to see some images to help visualise this. If you want, ping me on Discord and I can share some.

**Comment by mgi388** [comment]
> (Also, the next update will better support 3D sprites out of the box so that might help with your project)

@merwaaan just looked at the 3d branch. I'm very interested in this :) flipping and anchors are what are missing from https://github.com/FraserLee/bevy_sprite3d/issues/24 that I need.

**Comment by merwaaan** [comment]
Thanks for your detailed insights @mgi388 .

I've looked furthermore into those animation variants and indeed there doesn't seem to be a definitive terminology/methology around them, everyone seems to have their own recipes.

The main challenge would be to add this feature without increasing the library complexity too much. For the moment, I'm leaning towards externalizing it into a higher-level mechanism (something like a state machine) that might be provided or not by the library.

I guess that this would be quite easy to implement once the API makes it easier to control animations while they're playing. Especially if we have something like `animator.set_animation_progress(some_normalized_value)` to sync variants when switching from one to another.

Anyway, I'll finish up the 3D branch in the next days, and then work on those improvements.

**Comment by mgi388** [comment]
@merwaaan yeah my biggest concern with my proposal or idea here is that I can’t find any existing prior art for this pattern (maybe it’s something that exists more in 3D animation code/patterns and so I’m not looking in the right place by searching only “sprite animation variants”.

But yes any ability by this library to update some sort of progress to avoid resetting would be welcomed even if that means I have to build on top of this library myself (which is fine). 

In the meantime, I will keep iterating on my fork in my project and see if I can come up with a design that doesn’t feel complex and seems like it should be added to this library.

**Comment by merwaaan** [comment]
The latest version exposes a `progress` field in the `SpritesheetAnimation` component that gives more control over playback. That should make it way easier for you to support variants.

There's a new `SpritesheetAnimation::switch()` method that changes to another animation and starts from the first frame and if you need more control, you can set `animation_id` and `progress.frame` manually.
